fix: switch to label

diff --git a/.github/actions/renovate-readiness/action.yaml b/.github/actions/renovate-readiness/action.yaml
--- a/.github/actions/renovate-readiness/action.yaml
+++ b/.github/actions/renovate-readiness/action.yaml
@@ -8,14 +8,10 @@ runs:
   using: composite
   steps:
     # This is current a stub for future logic that would auto-detect readiness
-    # In lieu of that, we require an engineer to review changes and manually switch a renovate PR out of draft mode
-    - name: Check if PR is in draft
+    # In lieu of that, we require an engineer to review changes and manually add the `renovate: ready` label
+    - name: Check if PR has the ready label
+      if: ${{ ! contains(github.event.pull_request.labels.*.name, 'renovate: ready') }}
       run: |
-        echo "Checking if this PR is in draft..."
-        if [[ "${{ github.event.pull_request.draft }}" == "true" ]]; then
-          echo "This PR is still in draft. Failing job."
-          exit 1
-        else
-          echo "PR is not in draft. Continuing..."
-        fi
+        echo "This PR is not ready to run CI. Failing job."
+        exit 1
       shell: bash
